version: '3.8'

services:
  mysql_master:
    image: mysql:8.3.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: master_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/master:/var/lib/mysql
    networks:
      - mysql_network

  mysql_slave:
    image: mysql:8.3.0
    container_name: mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: slave_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    depends_on:
      - mysql_master
    ports:
      - "3307:3306"
    volumes:
      - ./data/slave:/var/lib/mysql
    networks:
      - mysql_network

networks:
  mysql_network:
