version: '3.8'

services:
  mysql_master:
    image: mysql:8.3.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: master_password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - ./data/master:/var/lib/mysql
      - ./config/master:/etc/mysql/conf.d
      - ./init/master:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

  mysql_slave1:
    image: mysql:8.3.0
    container_name: mysql_slave1
    environment:
      MYSQL_ROOT_PASSWORD: slave_password
      MYSQL_DATABASE: mydatabase
    depends_on:
      - mysql_master
    ports:
      - "3307:3306"
    volumes:
      - ./data/slave1:/var/lib/mysql
      - ./config/slave1:/etc/mysql/conf.d
      - ./init/slave1:/docker-entrypoint-initdb
    networks:
      - mysql_network

  mysql_slave2:
    image: mysql:8.3.0
    container_name: mysql_slave2
    environment:
      MYSQL_ROOT_PASSWORD: slave_password
      MYSQL_DATABASE: mydatabase
    depends_on:
      - mysql_master
    ports:
      - "3308:3306"
    volumes:
      - ./data/slave2:/var/lib/mysql
      - ./config/slave2:/etc/mysql/conf.d
      - ./init/slave1:/docker-entrypoint-initdb
    networks:
      - mysql_network

networks:
  mysql_network:
    ipam:
      driver: default
      config:
        - subnet: 10.250.0.0/16
